name: potato
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-271.4.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.0.0-dev.4

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  auto_route: ^4.2.1
  get_it: ^7.2.0
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^4.2.1
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

  assets:
    - .env
